# big-query:
#   target: dev
#   outputs:
#     dev:
#       type: bigquery
#       method: oauth
#       project: de-dtc-377713
#       schema: dbt_eli
#       location: EU

  # [profile-name]:
  #   target: [target-name]

  #   outputs:
  #     # 1. Use oauth flow
  #     [target-name-1]:
  #       type: bigquery
  #       method: oauth
  #       project: [GCP project id]
  #       schema: [dbt schema]
  #       threads: [between 1 and 8]
  #       timeout_seconds: 300

  #     # 2. use a service account keyfile
  #     [target-name-2]:
  #       type: bigquery
  #       method: service-account
  #       project: [GCP project id]
  #       schema: [dbt schema]
  #       threads: [between 1 and 8]
  #       keyfile: [/path/to/bigquery/keyfile.json]